/* Shared, in-memory picker UI. Gameplay eligibility and recommendations belong to adapters. */
(()=>{'use strict';
const states=new Map(),configs=new Map();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function state(key,c={}){if(!states.has(key))states.set(key,{search:'',sort:c.defaultSort||c.sorts?.[0]?.id||'original',filters:{},recommended:false,direction:1,limit:48});return states.get(key)}
function query(key,c){const s=state(key,c);let list=c.items.filter(i=>{
 const text=(i.search||i.title||'').toLocaleLowerCase();
 return s.search.trim().toLocaleLowerCase().split(/\s+/).every(q=>text.includes(q))&&(!s.recommended||i.recommended)&&Object.entries(s.filters).every(([k,values])=>!values.length||values.some(v=>(i.facets?.[k]||[]).map(String).includes(v)));
});const sort=c.sorts?.find(x=>x.id===s.sort);if(sort?.compare)list=[...list].sort(sort.compare);return s.direction===-1?[...list].reverse():list}
function card(i){return `<button type="button" class="qp-card ${i.selected?'selected':''}" data-qp-item="${esc(i.id)}" aria-pressed="${!!i.selected}" ${i.disabled?'disabled':''}>${i.art||'<span class="qp-symbol" aria-hidden="true">◆</span>'}<span class="qp-copy"><strong>${esc(i.title)}</strong><small>${esc(i.description)}</small>${i.detailHTML||''}<span class="qp-badges">${i.recommended?'<em>推荐</em>':''}${i.selected?'<em>✓ 已选</em>':''}${i.disabled?'<em>不可选</em>':''}</span></span></button>`}
function html(key,c){configs.set(key,c);const s=state(key,c),list=query(key,c),sorts=c.sorts||[{id:'original',label:'原有顺序'}],count=Object.values(s.filters).reduce((a,v)=>a+v.length,0),sort=sorts.find(x=>x.id===s.sort)||sorts[0];
 const facets=(c.facets||[]).map(f=>{const vals=f.options||[...new Set(c.items.flatMap(i=>i.facets?.[f.id]||[]))].sort((a,b)=>String(a).localeCompare(String(b),'zh-CN')).map(v=>({value:String(v),label:String(v)}));return `<fieldset><legend>${esc(f.label)}</legend><div class="qp-chips">${vals.map(v=>`<button type="button" data-qp-filter="${esc(f.id)}" data-value="${esc(v.value)}" aria-pressed="${(s.filters[f.id]||[]).includes(String(v.value))}">${esc(v.label)}</button>`).join('')||'<small>暂无可筛选内容</small>'}</div></fieldset>`}).join('');
 return `<section class="qp" data-qp="${esc(key)}" aria-label="${esc(c.title)}" ${c.close?'role="dialog" aria-modal="true"':''}><div class="qp-heading"><b>${esc(c.title)}</b>${c.close?'<button type="button" data-qp-close aria-label="关闭选择">关闭 ×</button>':''}</div><div class="qp-toolbar"><label class="qp-search">Search · 搜索<input type="search" data-qp-search aria-label="${esc(c.title)}搜索" placeholder="${esc(c.placeholder||'名字 / 技能 / #编号')}" value="${esc(s.search)}"></label><details data-qp-panel="sort"><summary>Sort · ${esc(sort.label)}</summary><div class="qp-chips">${sorts.map(x=>`<button type="button" data-qp-sort="${esc(x.id)}" aria-pressed="${s.sort===x.id}">${esc(x.label)}</button>`).join('')}<button type="button" data-qp-direction aria-pressed="${s.direction===-1}">⇅ 反转顺序</button></div></details><details data-qp-panel="filter"><summary>Filter · 筛选${count?' ('+count+')':''}</summary><small>同组条件取其一，不同组同时满足</small>${facets||'<small>此列表没有额外分类条件</small>'}</details></div><div class="qp-actions"><button type="button" data-qp-clear>清除筛选</button><button type="button" data-qp-recommended aria-pressed="${s.recommended}" ${c.recommendationNote? '':'disabled'}>只看推荐</button><span>${esc(c.recommendationNote||'此列表没有推荐规则')}</span></div><p class="qp-count" role="status">显示 ${list.length} / ${c.items.length} 项${c.items.some(i=>i.selected)?' · 已选 '+c.items.filter(i=>i.selected).length+' 项（筛选不会取消选择）':''}</p><div class="qp-grid">${list.slice(0,s.limit).map(i=>c.card?c.card(i):card(i)).join('')||'<p class="qp-empty">没有符合条件的结果。试试清除筛选。</p>'}</div>${list.length>s.limit?'<button type="button" class="qp-more" data-qp-more>再显示 48 项</button>':''}</section>`;
}
function mount(host,key,c){if(!host)return;const markup=html(key,c);if(host._qpHTML===markup)return;const active=host.contains(document.activeElement)?document.activeElement:null;const search=active?.matches('[data-qp-search]');const pos=search?active.selectionStart:null;const scroll=host.scrollTop;const open=[...host.querySelectorAll('details[open]')].map(d=>d.dataset.qpPanel);host.innerHTML=markup;host._qpHTML=markup;for(const id of open)host.querySelector(`[data-qp-panel="${id}"]`)?.setAttribute('open','');host.scrollTop=scroll;if(search){const el=host.querySelector('[data-qp-search]');el?.focus({preventScroll:true});el?.setSelectionRange(pos,pos)}}
function refresh(root,key){const c=configs.get(key);const focus=document.activeElement;const attrs=['data-qp-search','data-qp-filter','data-qp-sort','data-qp-clear','data-qp-recommended','data-qp-more','data-qp-direction'];const attr=attrs.find(a=>focus?.hasAttribute(a));const value=attr?focus.getAttribute(attr):null;const filterValue=focus?.getAttribute('data-value');const cursor=attr==='data-qp-search'?focus.selectionStart:null;const opens=[...root.querySelectorAll('details[open]')].map(d=>d.dataset.qpPanel);const parent=root.parentElement,scroll=parent.scrollTop;root.outerHTML=html(key,c);const next=[...parent.querySelectorAll('[data-qp]')].find(x=>x.dataset.qp===key);for(const p of opens)next.querySelector(`[data-qp-panel="${p}"]`)?.setAttribute('open','');const target=attr?[...next.querySelectorAll(`[${attr}]`)].find(x=>x.getAttribute(attr)===value&&(!filterValue||x.getAttribute('data-value')===filterValue)):null;target?.focus({preventScroll:true});if(cursor!=null)target?.setSelectionRange(cursor,cursor);parent.scrollTop=scroll;c.onFilter?.()}
document.addEventListener('input',e=>{if(!e.target.matches('[data-qp-search]')||e.isComposing)return;const root=e.target.closest('[data-qp]'),key=root.dataset.qp;state(key).search=e.target.value;state(key).limit=48;refresh(root,key)});
document.addEventListener('compositionend',e=>{if(e.target.matches('[data-qp-search]'))e.target.dispatchEvent(new Event('input',{bubbles:true}))});
document.addEventListener('click',e=>{const root=e.target.closest?.('[data-qp]');if(!root)return;const key=root.dataset.qp,c=configs.get(key),s=state(key),b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-qp-close')){e.stopImmediatePropagation();c.close?.();return}if(b.hasAttribute('data-qp-item')){e.stopImmediatePropagation();const i=c.items.find(i=>String(i.id)===b.dataset.qpItem);if(i&&!i.disabled)c.choose?.(i);return}
 let changed=true;if(b.hasAttribute('data-qp-sort'))s.sort=b.dataset.qpSort;else if(b.hasAttribute('data-qp-direction'))s.direction*=-1;else if(b.hasAttribute('data-qp-filter')){const k=b.dataset.qpFilter,v=b.dataset.value,a=s.filters[k]||[];s.filters[k]=a.includes(v)?a.filter(x=>x!==v):[...a,v]}else if(b.hasAttribute('data-qp-clear')){s.filters={};s.search='';s.recommended=false}else if(b.hasAttribute('data-qp-recommended'))s.recommended=!s.recommended;else if(b.hasAttribute('data-qp-more'))s.limit+=48;else changed=false;if(changed){e.preventDefault();e.stopImmediatePropagation();refresh(root,key)}});
document.addEventListener('keydown',e=>{if(e.key==='Tab'){const root=e.target.closest?.('[data-qp][role=dialog]');if(root){const els=[...root.querySelectorAll('button:not(:disabled),input,summary')].filter(x=>x.getClientRects().length);const edge=e.shiftKey?els[0]:els.at(-1);if(e.target===edge){e.preventDefault();(e.shiftKey?els.at(-1):els[0])?.focus()}}}if(e.key==='Escape'){const root=e.target.closest?.('[data-qp]');if(root)configs.get(root.dataset.qp)?.close?.()}});
window.QinsterPicker={html,mount,query,state,esc,card};
})();
