from pathlib import Path
p=Path('v199-roguelike-expedition.js')
s=p.read_text(encoding='utf-8')
old="function trainingHTML(run){\n  const choices=run.trainingChoices||[],gain=Math.round(trainingGainMultiplier(run)*100),extra=Math.max(0,trainingChoiceCount(run)-3);\n  return `${runHeader(run)}${runInventoryHTML(run)}${teamHTML(run)}<section class=\"rg-panel\"><div class=\"rg-title\"><div><b>▲ 训练营</b><small>选择1项；训练强化只在本次远征永久生效</small></div><span>${choices.length}选1 · 当前训练效率 ${gain}%${extra?' · 额外候选 +'+extra:''}</span></div><div class=\"rg-event-picks\">${choices.map((c,i)=>`<button class=\"secondary\" data-rg-training-choice=\"${i}\"><b>${c.monsterName}</b><small>${STAT[c.stat]} +${c.value}${c.kind==='pct'?'%':''}${Math.abs(c.value-c.raw)>.01?` · 基础 ${c.raw}${c.kind==='pct'?'%':''}`:''}</small></button>`).join('')}</div><p class=\"rg-note\">基础训练范围：百分比 +1%～5%，固定值 +1～20。教官徽章提高候选数与训练量；倦怠会降低训练量。</p></section>`;\n}"
if old not in s:
    raise SystemExit('trainingHTML target not found')
new="function trainingHTML(run){\n  const choices=run.trainingChoices||[],gain=Math.round(trainingGainMultiplier(run)*100),extra=Math.max(0,trainingChoiceCount(run)-3);\n  const t=activeTeam(run),byId=id=>t.find(m=>String(m.id)===String(id));\n  const finalValue=c=>{const m=byId(c.monsterId);if(!m)return null;const base=trainedBaseStats(m,run)[c.stat]||0;return c.kind==='pct'?Math.round(base*(1+c.value/100)*10)/10:Math.round((base+c.value)*10)/10};\n  return `${runHeader(run)}${runInventoryHTML(run)}${teamHTML(run)}<section class=\"rg-panel\"><div class=\"rg-title\"><div><b>▲ 训练营</b><small>选择1项；训练强化只在本次远征永久生效</small></div><span>${choices.length}选1 · 当前训练效率 ${gain}%${extra?' · 额外候选 +'+extra:''}</span></div><div class=\"rg-event-picks\">${choices.map((c,i)=>{const m=byId(c.monsterId),fv=finalValue(c),cur=m?Math.round((trainedBaseStats(m,run)[c.stat]||0)*10)/10:null;return `<button class=\"secondary rg-training-pick\" data-rg-training-choice=\"${i}\">${m?R()?.sprite?.(m.species,m.tint,m.shiny,m.specialColor)||'':''}<span class=\"rg-training-copy\"><b>${c.monsterName}</b><small>#${c.monsterId} · ${STAT[c.stat]}</small><strong class=\"rg-training-gain\">+${c.value}${c.kind==='pct'?'%':''}</strong>${cur!=null&&fv!=null?`<small class=\"rg-training-final\">${STAT[c.stat]}：${cur} → <b>${fv}</b></small>`:''}${Math.abs(c.value-c.raw)>.01?`<small>基础训练：+${c.raw}${c.kind==='pct'?'%':''}</small>`:''}</span></button>`}).join('')}</div><p class=\"rg-note\">基础训练范围：百分比 +1%～5%，固定值 +1～20。教官徽章提高候选数与训练量；倦怠会降低训练量。</p></section>`;\n}"
s=s.replace(old,new,1)
needle='.rg-event-picks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}'
css='.rg-training-pick{display:grid;grid-template-columns:72px minmax(0,1fr);gap:10px;align-items:center;text-align:left;padding:10px;background:#d8ddd5;border-color:#6f786d}.rg-training-pick .sprite{width:64px!important;margin:auto}.rg-training-copy{display:grid;gap:3px}.rg-training-copy b,.rg-training-copy small,.rg-training-copy strong{display:block}.rg-training-gain{font-size:18px;color:#2f6d3d}.rg-training-final{margin-top:2px;padding-top:4px;border-top:1px dashed #8b9388;color:#464b47}.rg-training-final b{display:inline;color:#2f6d3d}@media(max-width:760px){.rg-training-pick{grid-template-columns:60px minmax(0,1fr)}.rg-training-pick .sprite{width:54px!important}}'
if needle in s and css not in s:
    s=s.replace(needle,needle+css,1)
for oldv in ["version:'v233-training-node-ui'","version:'v232-event-odds-rewards'","version:'v231-expedition-stat-grid'"]:
    s=s.replace(oldv,"version:'v234-training-final-value'")
p.write_text(s,encoding='utf-8')
for fp in ['game.js','index.html']:
    q=Path(fp);t=q.read_text(encoding='utf-8');t=t.replace('v233','v234').replace('v232','v234');q.write_text(t,encoding='utf-8')
print('v234 training final value preview applied')
