from pathlib import Path
import re
p=Path('v199-roguelike-expedition.js')
s=p.read_text(encoding='utf-8')
new_battle="""function battle(run,kind){const zone=z(run.zone),t=activeTeam(run),elite=kind==='elite',boss=kind==='boss',mult=zone.enemy*(1+run.stage*.085)*(elite?1.22:1)*(boss?1.48:1),enemyMax=Math.round(240*mult+zone.tier*70),enemyAtk=55*mult+zone.tier*11,enemyDef=45*mult+zone.tier*9;let enemy=enemyMax,round=0,firstGuard=true;const logs=[];while(enemy>0&&round<8&&t.some(m=>hpPct(run,m.id)>0)){round++;const aliveNow=t.map((m,orig)=>({m,orig,hp:hpPct(run,m.id)})).filter(x=>x.hp>0);let dmg=0;aliveNow.forEach((x,dynPos)=>{const p=combatValue(x.m,dynPos,run),crit=Math.random()<Math.min(.38,p.luck/1600),raw=(p.atk*.22+p.spd*.06+p.luck*.025)*(crit?1.65:1),hit=Math.max(7,raw-enemyDef*.07);dmg+=hit});enemy=Math.max(0,enemy-dmg);logs.push(`第 ${round} 回合：队伍造成 ${Math.round(dmg)} 伤害${enemy<=0?'，敌人倒下。':''}`);if(enemy<=0)break;const alive=t.map((m,orig)=>({m,orig,hp:hpPct(run,m.id)})).filter(x=>x.hp>0).map((x,dynPos)=>({...x,dynPos}));const roll=Math.random();let target=roll<.64?alive[0]:roll<.88?(alive[1]||alive[0]):(alive[2]||alive[1]||alive[0]);const p=combatValue(target.m,target.dynPos,run);let incoming=Math.max(5,enemyAtk-p.def*.08);if(firstGuard&&(relicMods(run).firstGuard||0)){incoming*=1-relicMods(run).firstGuard;firstGuard=false}const hpLoss=Math.min(42,incoming/(65+p.con*.22)*100);run.hp[target.m.id]=Math.max(0,hpPct(run,target.m.id)-hpLoss);logs.push(`敌人反击 ${monsterName(target.m)}（${['前卫','中卫','后卫'][target.dynPos]}），远征生命 -${Math.round(hpLoss)}%。`);if(run.hp[target.m.id]<=0)logs.push(`${monsterName(target.m)} 倒下，后方队员自动向前补位。`)}const win=enemy<=0;if(win){const base=Math.round((1100+run.stage*330)*(elite?1.7:1)*(boss?2.8:1)*nodeRewardScale(zone,run.stage));run.energy+=base;if(elite)run.tempBadges+=Math.max(1,Math.round(zone.badge*.5));const heal=relicMods(run).heal||0;if(heal)t.forEach(m=>run.hp[m.id]=Math.min(100,hpPct(run,m.id)+heal*100));run.log.push(`${boss?'首领':elite?'精英':'战斗'}胜利：+${base} 灵能。`)}else run.log.push('战斗失败，远征被迫撤退。');run.battle={kind,enemyMax,enemyHp:enemy,rounds:round,logs,win};run.phase='battleResult';save()}"""
s,n=re.subn(r"function battle\(run,kind\)\{.*?\}\s*function offerRelic",new_battle+'\nfunction offerRelic',s,count=1,flags=re.S)
if n!=1: raise SystemExit('battle target not found')
new_finish="""function applyExpeditionLifeCost(run,cleared){const s=S();if(!s)return[];const byId=new Map((s.monsters||[]).map(m=>[m.id,m])),notes=[];for(const id of run.teamIds||[]){const m=byId.get(id);if(!m)continue;let loss=0;if(cleared)loss+=1;if(hpPct(run,id)<=0)loss+=1;if(loss>0){m.life=Math.max(0,(Number(m.life)||0)-loss);notes.push(`${monsterName(m)} -${loss}生命${cleared&&hpPct(run,id)<=0?'（通关1 + 倒下1）':cleared?'（完成远征）':'（远征倒下）'}`)}}return notes}
function finish(run,cleared=false,defeated=false,choice=''){const s=S(),e=ensure();if(!s||!e)return;const zone=z(run.zone),fraction=cleared?1:defeated?.35:.65,payout=Math.round(run.energy*fraction),badge=cleared?zone.badge+run.tempBadges:Math.floor(run.tempBadges*fraction);s.energy=(Number(s.energy)||0)+payout;e.badges+=badge;for(const k of Object.keys(run.materials))e.loot[k]=(e.loot[k]||0)+Math.floor((run.materials[k]||0)*fraction);const lifeNotes=applyExpeditionLifeCost(run,cleared);e.rogueLast={zone:zone.name,cleared,defeated,payout,badge,relics:run.relics?.length||0,time:Date.now(),choice,lifeNotes};e.rogueActive=null;const lifeText=lifeNotes.length?' · '+lifeNotes.join('；'):'';save((cleared?`远征通关！带回 ${payout} 灵能、徽章 ×${badge}。`:`远征结束，带回 ${payout} 灵能。`)+lifeText)}"""
s,n=re.subn(r"function finish\(run,cleared=false,defeated=false,choice=''\)\{.*?\}\s*function abandon",new_finish+'\nfunction abandon',s,count=1,flags=re.S)
if n!=1: raise SystemExit('finish target not found')
s=s.replace("['前排','中排','后排']","['前卫','中卫','后卫']")
s=s.replace('前排更容易被攻击，中排均衡，后排更安全且部分遗物会强化','前卫承担主要火力；倒下后中卫自动补位，再由后卫补上。部分遗物会强化站位')
s=s.replace('1号前排、2号中排、3号后排','1号前卫、2号中卫、3号后卫')
p.write_text(s,encoding='utf-8')
